### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by gorogm** [bhklab/PymRMRe#6]
The documentation for the two functions seem to be the same. What's the difference?

The example shows that 'import Pymrmre' should work, but on Ubuntu actually it worked with lowercase letter only.

**Comment by ChristopherEeles** [comment]
Hi @gorogm, 

I just opened a pull request updating the documentation. I have updated the import statement to use the lowercase version. As far as I can tell, `mrmr_ensemble_survival` is an incomplete package feature. The only difference between it and the normal `mrmr_ensemble` function was that it expected targets to have only two columns, event, and survival_time. I removed this function from the main documentation since it has a subset of features of the `mrmr_ensemble` function.

I recommend just using the `mrmr_ensemble` function in all cases since you are free to use survival data as whichever features you like.

Best,
Christopher Eeles

**Comment by gorogm** [comment]
Great, thanks a lot!
